language: ruby
rvm: 2.7.1
gemfile: Gemfile
services:
  - postgresql
env: DB=postgres
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
before_script:
  - psql --version
  - psql -c 'create database prograils_app_test;' -U postgres
script: bundle exec rake spec
services:
  - postgresql
test:
  adapter: postgresql
  database: prograils_app_test
addons:
  postgresql: '11.2'
