language: ruby

services:
  - postgresql

env:
  - DB=postgres

addons:
  postgresql: '12.3'

rvm:
  - 2.7.1

before_install:
  - gem install bundler

gemfile: Gemfile

before_script:
  - psql -c 'create database prograils_app_test;'

script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
