# language: ruby
# rvm: 2.7.1
# gemfile: Gemfile
# services:
#   - postgresql
# env: DB=postgres
# script:
#   - bundle exec rails db:create db:migrate RAILS_ENV=test
#   - bundle exec rake spec
#   - bundle exec rubocop --config .rubocop.yml
# services:
#   - postgresql
# addons:
#   postgresql: '9.6'
# env:
#   global:
#   - PGPORT=5433

services:
  - postgresql
addons:
  postgresql: '9.6'
before_script:
  - cp config/database.yml.travis config/database.yml
before_install:
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.6
language: ruby
rvm:
  - 2.7.1
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
