language: ruby
rvm: 2.7.1
gemfile: Gemfile
services:
  - postgresql
env: DB=postgres
script:
  - bundle exec rails db:create db:migrate RAILS_ENV=test
  - bundle exec rake spec
  - bundle exec rubocop --config .rubocop.yml
services:
  - postgresql
addons:
  postgresql: '9.6'
env:
  global:
  - PGPORT=5433
